project:
  type: website
  output-dir: docs

website:
  title: "My Analytics Project"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd #person A
        text: Home
      - href: abstract.qmd #person B
        text: Abstract



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true