project:
  type: website
  output-dir: docs

website:
  title: "My Data Analysis Project"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: abstract.qmd
        text: Abstract


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true